# Generated by Django 2.2.28 on 2025-02-13 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20250213_1725'),
    ]

    operations = [
    ]
