# Generated by Django 2.2.28 on 2025-02-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_update_category_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category name', max_length=128, unique=True),
        ),
    ]
